# Generated by Django 4.1.2 on 2022-10-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Categories')),
                ('title', models.CharField(max_length=100)),
                ('descreption', models.TextField()),
                ('vaccency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Jobsection')),
                ('title', models.CharField(max_length=200)),
                ('descreption', models.TextField()),
                ('vaccency', models.IntegerField()),
                ('experience', models.TextField()),
                ('document', models.TextField()),
                ('skill', models.TextField()),
                ('language', models.TextField()),
                ('salary', models.TextField()),
                ('age', models.TextField()),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='home.categories')),
            ],
        ),
    ]
